name: Build and Push Docker Image

on:
  push:
    tags: [ "*" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Extract version from Git ref
        id: vars
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV
          fi
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          no-cache: true
          tags: |
            allinssl/allinssl:${{ env.VERSION }}
            allinssl/allinssl:latest
      - name: Clean up Docker node cache
        run: |
          curl -X POST "${{ secrets.DOCKER_CACHE_CLEANUP_URL }}" -F="repo=docker.io" -F "reference=latest" -F "name=allinssl/allinssl"
